#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# Knowledge Atlas — University VM Deployment Script
# ═══════════════════════════════════════════════════════════════
# Run this on the university VM (or from David's Mac via SSH).
#
# Prerequisites:
#   - Python 3.10+ on the VM
#   - 5TB mount at /mnt/ka_storage (or set KA_STORAGE_ROOT)
#   - Git access to the repo
#
# Usage:
#   bash scripts/deploy_to_vm.sh              # deploy with defaults
#   bash scripts/deploy_to_vm.sh --port 8080  # custom port
# ═══════════════════════════════════════════════════════════════

set -euo pipefail

# ── Defaults ──
PORT="${KA_PORT:-8765}"
HOST="${KA_HOST:-0.0.0.0}"
STORAGE_ROOT="${KA_STORAGE_ROOT:-/mnt/ka_storage}"
REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
VENV_DIR="${REPO_DIR}/.venv"
LOG_DIR="${REPO_DIR}/logs"
PID_FILE="${REPO_DIR}/ka_server.pid"

# ── Parse args ──
while [[ $# -gt 0 ]]; do
  case "$1" in
    --port) PORT="$2"; shift 2 ;;
    --host) HOST="$2"; shift 2 ;;
    --storage) STORAGE_ROOT="$2"; shift 2 ;;
    *) echo "Unknown arg: $1"; exit 1 ;;
  esac
done

echo "═══════════════════════════════════════════════════"
echo "  Knowledge Atlas Deployment"
echo "═══════════════════════════════════════════════════"
echo "  Repo:        ${REPO_DIR}"
echo "  Port:        ${PORT}"
echo "  Host:        ${HOST}"
echo "  Storage:     ${STORAGE_ROOT}"
echo "  Venv:        ${VENV_DIR}"
echo "═══════════════════════════════════════════════════"

# ── Step 1: Check Python ──
echo ""
echo "[1/7] Checking Python..."
if command -v python3 &>/dev/null; then
  PYTHON=python3
elif command -v python &>/dev/null; then
  PYTHON=python
else
  echo "ERROR: Python 3 not found. Install Python 3.10+."
  exit 1
fi
PY_VERSION=$($PYTHON --version 2>&1)
echo "  Found: ${PY_VERSION}"

# ── Step 2: Create virtual environment ──
echo ""
echo "[2/7] Setting up virtual environment..."
if [ ! -d "${VENV_DIR}" ]; then
  $PYTHON -m venv "${VENV_DIR}"
  echo "  Created new venv at ${VENV_DIR}"
else
  echo "  Using existing venv at ${VENV_DIR}"
fi
source "${VENV_DIR}/bin/activate"

# ── Step 3: Install dependencies ──
echo ""
echo "[3/7] Installing dependencies..."
pip install --upgrade pip -q
pip install \
  fastapi \
  uvicorn \
  "python-jose[cryptography]" \
  "passlib[bcrypt]" \
  python-multipart \
  aiofiles \
  -q
echo "  Dependencies installed ✓"

# ── Step 4: Create storage directories ──
echo ""
echo "[4/7] Creating storage directories..."
mkdir -p "${STORAGE_ROOT}/quarantine"
mkdir -p "${STORAGE_ROOT}/pdf_collection"
mkdir -p "${STORAGE_ROOT}/rejected"
mkdir -p "${LOG_DIR}"
echo "  ${STORAGE_ROOT}/quarantine     ✓"
echo "  ${STORAGE_ROOT}/pdf_collection ✓"
echo "  ${STORAGE_ROOT}/rejected       ✓"
echo "  ${LOG_DIR}                     ✓"

# ── Step 5: Update ka_config.js for production ──
echo ""
echo "[5/7] Updating ka_config.js..."
# Detect the VM's hostname/IP for the config
VM_HOSTNAME=$(hostname -f 2>/dev/null || hostname)
VM_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")
API_URL="http://${VM_IP}:${PORT}"

cat > "${REPO_DIR}/ka_config.js" << JSEOF
/**
 * Knowledge Atlas — Site Configuration (Production)
 * Generated by deploy_to_vm.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
 */
window.__KA_CONFIG__ = {
  apiBase: '${API_URL}',
  siteName: 'Knowledge Atlas',
  courseCode: 'COGS 160',
  quarter: 'Spring 2026',
};
JSEOF
echo "  API base set to: ${API_URL}"

# ── Step 6: Stop existing server if running ──
echo ""
echo "[6/7] Checking for existing server..."
if [ -f "${PID_FILE}" ]; then
  OLD_PID=$(cat "${PID_FILE}")
  if kill -0 "${OLD_PID}" 2>/dev/null; then
    echo "  Stopping existing server (PID ${OLD_PID})..."
    kill "${OLD_PID}"
    sleep 2
  fi
  rm -f "${PID_FILE}"
fi

# ── Step 7: Start server ──
echo ""
echo "[7/7] Starting server..."
export KA_STORAGE_ROOT="${STORAGE_ROOT}"
export KA_SECRET_KEY="${KA_SECRET_KEY:-$(openssl rand -hex 32)}"

cd "${REPO_DIR}"
nohup "${VENV_DIR}/bin/python" ka_auth_server.py \
  > "${LOG_DIR}/ka_server_$(date +%Y%m%d_%H%M%S).log" 2>&1 &
SERVER_PID=$!
echo "${SERVER_PID}" > "${PID_FILE}"

sleep 2

# Verify it's running
if kill -0 "${SERVER_PID}" 2>/dev/null; then
  echo ""
  echo "═══════════════════════════════════════════════════"
  echo "  ✓ Server running!"
  echo "  PID:     ${SERVER_PID}"
  echo "  URL:     http://${VM_IP}:${PORT}"
  echo "  Docs:    http://${VM_IP}:${PORT}/docs"
  echo "  Log:     ${LOG_DIR}/ka_server_*.log"
  echo ""
  echo "  To stop:  kill \$(cat ${PID_FILE})"
  echo "  To check: curl http://localhost:${PORT}/health"
  echo "═══════════════════════════════════════════════════"
else
  echo ""
  echo "ERROR: Server failed to start. Check logs:"
  echo "  tail -50 ${LOG_DIR}/ka_server_*.log"
  exit 1
fi
